server:
  port: 7777
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/han_blog?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: qs64cvNFs9VaME_QPAxetN3G4nktYGf6tTtn4z5N
  secretKey: 1XnXATjilA3FJmiESLYECv1jui8MU2UZjkD9eYrT
  bucket: hanblog2